services:

  postgres:
    image: postgres:17
    container_name: microservice-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: microservice_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: microservice-backend
    restart: unless-stopped
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=microservice-postgres;Port=5432;Database=microservice_hub;Username=postgres;Password=postgres123
      - ApisixAdmin__BaseUrl=http://apisix-gateway:9180
      - ApisixAdmin__ApiKey=your-super-secret-admin-key-change-this
      - Email__SmtpHost=smtp.gmail.com
      - Email__SmtpPort=587
      - Email__SmtpUser=yogeshunlock0991@gmail.com
      - Email__SmtpPassword=fods anqo dbie dune
      - Email__FromAddress=yogeshunlock0991@gmail.com
      - Email__FromName=PayPoint India


  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: microservice-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  postgres-data:
